---
clients:
  host1:
    hostname: host1.example.com
    port: 8443
    ssl: true
    api_key: ABCD1234
  host2:
    hostname: host2.example.com
    port: 8080
    ssl: false
    api_key: insecure_key
